site_name: syn
repo_url: https://github.com/wraith1995/syn
site_url: https://wraith1995.github.io/syn
site_description: erm
site_author: Teodoro Collin
edit_uri: edit/main/docs/
repo_name: wraith1995/syn
copyright: Maintained by <a href="https://wraith1995.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wraith1995/syn
    - icon: fontawesome/brands/python
      link: https://pypi.com/project/syn

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true